name       : ceres-solver
version    : 2.0.0
release    : 1
source     :
    - http://ceres-solver.org/ceres-solver-2.0.0.tar.gz : 10298a1d75ca884aa0507d1abb0e0f04800a92871cd400d4c361b56a777a7603
license    :
    - Apache-2.0
    - BSD-3-Clause
component  : programming.library
summary    : A nonlinear least squares minimizer
description: |
    Ceres Solver is an open source C++ library for modeling and solving large, complicated optimization problems. It can be used to solve Non-linear Least Squares problems with bounds constraints and general unconstrained optimization problems.
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(gflags)
    - pkgconfig(libglog)
    - pkgconfig(openblas)
    - suitesparse-devel
rundeps    :
    - devel :
        - eigen3
        - gflags-devel
        - glog-devel
        - openblas-devel
        - suitesparse-devel
setup      : |
    %cmake_ninja \
        -DEIGENSPARSE=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_TESTING=OFF \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_BENCHMARKS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
